name: house
dependencies:
- appnope=0.1.0=py35_0
- conda-forge::altair=1.0.0=py35_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py35_0
- conda-forge::brewer2mpl=1.4.1=py35_2
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::entrypoints=0.2.2=py35_0
- conda-forge::ggplot=0.11.2=py35_0
- conda-forge::ipykernel=4.5.0=py35_0
- conda-forge::ipython=5.1.0=py35_1
- conda-forge::ipython_genutils=0.1.0=py35_0
- conda-forge::ipywidgets=5.2.2=py35_2
- conda-forge::jinja2=2.8=py35_1
- conda-forge::jsonschema=2.5.1=py35_0
- conda-forge::jupyter_client=4.4.0=py35_0
- conda-forge::jupyter_console=5.0.0=py35_0
- conda-forge::jupyter_core=4.2.0=py35_0
- conda-forge::libsodium=1.0.10=0
- conda-forge::markupsafe=0.23=py35_0
- conda-forge::mistune=0.7.3=py35_0
- conda-forge::nbconvert=4.2.0=py35_0
- conda-forge::nbformat=4.1.0=py35_0
- conda-forge::notebook=4.2.3=py35_0
- conda-forge::pexpect=4.2.1=py35_0
- conda-forge::pickleshare=0.7.3=py35_0
- conda-forge::prompt_toolkit=1.0.7=py35_0
- conda-forge::ptyprocess=0.5.1=py35_0
- conda-forge::pygments=2.1.3=py35_1
- conda-forge::pyzmq=15.4.0=py35_0
- conda-forge::qtconsole=4.2.1=py35_0
- conda-forge::simplegeneric=0.8.1=py35_0
- conda-forge::sip=4.18=py35_0
- conda-forge::terminado=0.6=py35_0
- conda-forge::tornado=4.4.2=py35_0
- conda-forge::traitlets=4.3.1=py35_0
- conda-forge::vega=0.4.2=py35_2
- conda-forge::wcwidth=0.1.7=py35_0
- conda-forge::widgetsnbextension=1.2.6=py35_3
- conda-forge::zeromq=4.1.5=0
- cycler=0.10.0=py35_0
- freetype=2.5.5=1
- icu=54.1=0
- jupyter=1.0.0=py35_3
- libpng=1.6.22=0
- matplotlib=1.5.3=np111py35_0
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pandas=0.19.0=np111py35_0
- patsy=0.4.1=py35_0
- pip=8.1.2=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- python.app=1.2=py35_4
- pytz=2016.7=py35_0
- qt=5.6.0=0
- readline=6.2=2
- scikit-learn=0.18=np111py35_0
- scipy=0.18.1=np111py35_0
- seaborn=0.7.1=py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - altair==1.0.0
  - backports.shutil-get-terminal-size==1.0.0
  - brewer2mpl==1.4.1
  - decorator==4.0.10
  - ggplot==0.11.2
  - ipykernel==4.5.0
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - markupsafe==0.23
  - mistune==0.7.3
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - nbstripout==0.2.8
  - notebook==4.2.3
  - pexpect==4.2.1
  - pickleshare==0.7.3
  - prompt-toolkit==1.0.7
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pytest-runner==2.9
  - pyzmq==15.4.0
  - qtconsole==4.2.1
  - simplegeneric==0.8.1
  - terminado==0.6
  - tornado==4.4.2
  - traitlets==4.3.1
  - vega==0.4.2
  - wcwidth==0.1.7
  - widgetsnbextension==1.2.6
  - statsmodels==0.8.0rc1
prefix: /Users/sinayoks/anaconda/envs/house
